steps:
  # Step 1: Checkout code from the repository.
  - name: 'gcr.io/cloud-builders/git'
    args:
      [
        'clone',
        '--single-branch',
        '--branch',
        'main',
        'https://github.com/PvitorDev/mks-backend-challenge',
      ]

  # Step 2: Install Node.js and Yarn.
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']

  # Step 3: Build the NestJS application.
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['start:prod']
